services:
  librosphere-api:
    image: ${DOCKER_REGISTRY-}librosphereapi
    container_name: LibroSphere.Api
    build:
      context: .
      dockerfile: src/LibroSphere.WebApi/Dockerfile
    depends_on:
      - librosphere-db
      - librosphere-idp

  librosphere-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: LibroSphere.Db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Pass123"
      MSSQL_SA_PASSWORD: "YourStrong!Pass123"
    ports:
      - "1433:1433"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - mssql-data:/var/opt/mssql

  librosphere-idp:
    image: quay.io/keycloak/keycloak:latest
    container_name: LibroSphere.Identity
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/librosphere-realm-export.json:/opt/keycloak/data/import/librosphere-realm-export.json
    ports:
      - "18080:8080"

volumes:
  mssql-data: