services:
  librosphere-api:
    container_name: LibroSphere.Api
    build:
      context: .
      dockerfile: src/LibroSphere.WebApi/Dockerfile
    env_file:
      - .env
    depends_on:
      - librosphere-db
      - redis
      - rabbitmq
    environment:
      ASPNETCORE_URLS: http://+:8080
      DB_HOST: librosphere-db
      ConnectionStrings__Redis: redis:6379,abortConnect=false
      RabbitMQ__Host: librosphere-rabbitmq
      Swagger__Enabled: "true"
    ports:
      - "8080:8080"
    restart: unless-stopped

  librosphere-worker:
    container_name: LibroSphere.Worker
    build:
      context: .
      dockerfile: src/LibroSphere.Worker/Dockerfile
    env_file:
      - .env
    depends_on:
      - librosphere-db
      - redis
      - rabbitmq
    environment:
      DB_HOST: librosphere-db
      ConnectionStrings__Redis: redis:6379,abortConnect=false
      RabbitMQ__Host: librosphere-rabbitmq
    restart: unless-stopped

  librosphere-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: LibroSphere.Db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Pass123"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: librosphere-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: librosphere-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  mssql-data:
  redis-data:
  rabbitmq_data: