version: "3.9"

services:
  librosphere-api:
    container_name: LibroSphere.Api
    build:
      context: .
      dockerfile: src/LibroSphere.WebApi/Dockerfile
    env_file:
      - .env
    depends_on:
      - librosphere-db
      - redis
      - rabbitmq
    environment:
      ASPNETCORE_URLS: http://+:${API_HTTP_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_SA_PASSWORD}
      ConnectionStrings__Redis: ${ConnectionStrings__Redis}
      RabbitMQ__Host: ${RabbitMQ__Host}
      RabbitMQ__Username: ${RabbitMQ__Username}
      RabbitMQ__Password: ${RabbitMQ__Password}
      Swagger__Enabled: ${Swagger__Enabled}
    ports:
      - "${API_HTTP_PORT}:${API_HTTP_PORT}"
    restart: unless-stopped

  librosphere-worker:
    container_name: LibroSphere.Worker
    build:
      context: .
      dockerfile: src/LibroSphere.Worker/Dockerfile
    env_file:
      - .env
    depends_on:
      - librosphere-db
      - redis
      - rabbitmq
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_SA_PASSWORD}
      ConnectionStrings__Redis: ${ConnectionStrings__Redis}
      RabbitMQ__Host: ${RabbitMQ__Host}
      RabbitMQ__Username: ${RabbitMQ__Username}
      RabbitMQ__Password: ${RabbitMQ__Password}
    restart: unless-stopped

  librosphere-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: LibroSphere.Db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_SA_PASSWORD}
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: librosphere-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: librosphere-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RabbitMQ__Username}
      RABBITMQ_DEFAULT_PASS: ${RabbitMQ__Password}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  mssql-data:
  redis-data:
  rabbitmq_data: